[package]

name = "bamboors"
version = "0.0.1"
authors = ["Daogang Tang <daogangtang@126.com>"]

[lib]
name = "bamboo"
path = "src/lib.rs"

[dependencies]

hyper = "*"
url = "*"
#route-recognizer = "*"

[dependencies.route-recognizer]

git = "https://github.com/daogangtang/route-recognizer.rs"
